title: Chris Bobbe
subtitle: Web Developer
description: Website and portfolio of Chris Bobbe, front-end web developer.

author: Chris Bobbe
email: csbobbe@gmail.com
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://chrisbobbe.github.io"

# Social settings

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
