title: fpmortals
subtitle: 한국어 번역
description: fpmortals의 한국어 번역 페이지

author: wooruang
email: wooruang@gmail.com
# avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://wooruang.github.io/fpmortals"

# Social settings
medium_url: https://medium.com/@wooruang
github_url: https://github.com/wooruang
linkedin_url: https://www.linkedin.com/in/hansaem-lee-47990a13b
twitter_url: https://twitter.com/wooruwang

# SEO settings
# google_analytics: 

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
